// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltjmuheitnlagqubaejz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0am11aGVpdG5sYWdxdWJhZWp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDM2NTUsImV4cCI6MjA2OTI3OTY1NX0.UvVDo9njOP5TEvgxJaCWTy13hdLdiYiaLzRMzk5jIJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});